/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import javax.swing.JOptionPane;
import fis_elearning.FIS_ELearning;

/**
 *
 * @author USER
 */
public class ELearningUI extends javax.swing.JFrame {

    FIS_ELearning resultados = new FIS_ELearning();



    /**
     * Creates new form ElearningUI
     */
    public ELearningUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcularButton = new javax.swing.JButton();
        bannerLabel = new javax.swing.JLabel();
        seleccionTextField = new javax.swing.JTextField();
        seleccionLabel = new javax.swing.JLabel();
        satisfaccionLabel = new javax.swing.JLabel();
        satisfaccionTextField = new javax.swing.JTextField();
        dificultadLabel = new javax.swing.JLabel();
        dificultadTextField = new javax.swing.JTextField();
        msgLabel = new javax.swing.JLabel();
        rangoSeleccionLabel = new javax.swing.JLabel();
        rangoSatisfaccionLabel1 = new javax.swing.JLabel();
        rangoDificultadLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoTextArea = new javax.swing.JTextArea();
        salirButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calcularButton.setText("Calcular");
        calcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularButtonActionPerformed(evt);
            }
        });

        bannerLabel.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        bannerLabel.setForeground(new java.awt.Color(0, 153, 204));
        bannerLabel.setText("E-Learning Recomendations");

        seleccionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionTextFieldActionPerformed(evt);
            }
        });
        seleccionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seleccionTextFieldKeyTyped(evt);
            }
        });

        seleccionLabel.setText("Ingrese la probabilidad de selección del curso:");

        satisfaccionLabel.setText("Ingrese el nivel de satisfacción esperado:");

        satisfaccionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisfaccionTextFieldActionPerformed(evt);
            }
        });

        dificultadLabel.setText("Ingrese la dificultad del curso:");

        dificultadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificultadTextFieldActionPerformed(evt);
            }
        });

        msgLabel.setText("Para conocer el costo y la duración del curso recomendados a elegir deberá evaluar los siguientes parámetros:");

        rangoSeleccionLabel.setForeground(new java.awt.Color(100, 100, 100));
        rangoSeleccionLabel.setText("La probabilidad de selección del curso entre 0 y 1, donde Baja: 0-0.3, Media Baja: 0.2-0.45, Media Alta: 0.4-0.7, Alta: 0.6-1 ");
        rangoSeleccionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rangoSatisfaccionLabel1.setForeground(new java.awt.Color(100, 100, 100));
        rangoSatisfaccionLabel1.setText("El nivel de satisfacción esperado entre 0 y 10, donde Muy Baja: 0-2, Baja: 1-4, Media: 3-7, Alta: 6-10 ");
        rangoSatisfaccionLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rangoDificultadLabel.setForeground(new java.awt.Color(100, 100, 100));
        rangoDificultadLabel.setText("La dificultad esperada entre 0 y 100, donde Principiante: 0-25, Intermedio: 20-60, Difícil: 45-80, Experto: 70-100");
        rangoDificultadLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        resultadoTextArea.setEditable(false);
        resultadoTextArea.setColumns(20);
        resultadoTextArea.setRows(5);
        jScrollPane1.setViewportView(resultadoTextArea);

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/base-de-conocimientos (3).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccionLabel)
                    .addComponent(dificultadLabel)
                    .addComponent(satisfaccionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dificultadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satisfaccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgLabel)
                            .addComponent(bannerLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(rangoDificultadLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(rangoSeleccionLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(rangoSatisfaccionLabel1)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salirButton)))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calcularButton)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(bannerLabel)
                .addGap(18, 18, 18)
                .addComponent(msgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rangoSeleccionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rangoDificultadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rangoSatisfaccionLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seleccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dificultadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dificultadLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(satisfaccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(satisfaccionLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(calcularButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(salirButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void calcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularButtonActionPerformed
        
        double seleccion = Double.parseDouble(seleccionTextField.getText().replace(",", "."));
        double satisfaccion = Double.parseDouble(satisfaccionTextField.getText().replace(",", "."));
        double dificultad = Double.parseDouble(dificultadTextField.getText().replace(",", "."));
        
        resultadoTextArea.setText(resultados.calcularCostoYDuracion(seleccion, satisfaccion, dificultad));
    }//GEN-LAST:event_calcularButtonActionPerformed

    private void seleccionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionTextFieldActionPerformed

    private void seleccionTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seleccionTextFieldKeyTyped

        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Valor inválido. Ingrese solo números");
        }
    }//GEN-LAST:event_seleccionTextFieldKeyTyped

    private void satisfaccionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisfaccionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satisfaccionTextFieldActionPerformed

    private void dificultadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificultadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dificultadTextFieldActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PropinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PropinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PropinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PropinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PropinaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerLabel;
    private javax.swing.JButton calcularButton;
    private javax.swing.JLabel dificultadLabel;
    private javax.swing.JTextField dificultadTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel rangoDificultadLabel;
    private javax.swing.JLabel rangoSatisfaccionLabel1;
    private javax.swing.JLabel rangoSeleccionLabel;
    private javax.swing.JTextArea resultadoTextArea;
    private javax.swing.JButton salirButton;
    private javax.swing.JLabel satisfaccionLabel;
    private javax.swing.JTextField satisfaccionTextField;
    private javax.swing.JLabel seleccionLabel;
    private javax.swing.JTextField seleccionTextField;
    // End of variables declaration//GEN-END:variables
}
